#%RAML 1.0
title: JVMX Spring REST Docs API Demo
baseUri: https://jvmx-spring-restdocs.herokuapp.com/v1
version: 1

types:
  Event:
    type: object
    properties:
      name: string
      place: string
    example:
      name: EDC
      place: CDMX
  Artist:
    type: object
    properties:
      name: string
      musicGenre: string
      albumes: array

resourceTypes:
  events:

/events:
  get:
    description: Retrieves a collection of events
    responses:
      200:
        body:
          application/json:
            schema: array
  post:
    description: Creates a new event
    body:
      application/json:
        type: Event
  /{eventId}:
    get:
      description: Retrieves a specific event
    /artists:
      get:
        description: Retrieves the artists that will participate in the event

/artists:
  get:
    description: Retrieves a collection of artists
  post:
    description: Submits an artists to the system
    body:
      application/json:
        type: Artist
  /{artistId}:
    get:
      description: Retrieves a specific event

/albums:
  /{albumId}:

/songs:
  /{songId}:

